version: 2
jobs:
  build:
    docker:
    - image: circleci/node:10

    steps:
      - checkout

      # restores dependencies from cache
      - restore_cache:
          keys:
          - yarn-deps-{{ checksum "yarn.lock" }}
      
      # install dependencies
      - run:
          command: yarn --frozen-lockfile
      
      # save dependencies to cache
      - save_cache:
          key: yarn-deps-{{ checksum "yarn.lock" }}
          paths:
          - node_modules
          
      - run: |
          yarn run lerna bootstrap
          yarn compile

      # save dependencies to cache
      - save_cache:
          key: packages-dist-{{ .Revision }}-{{ .Branch }}
          paths:
          - packages
  
  docker-build-push:
    docker:
    - image: docker:stable

    working_directory: /tmp/repo

    steps:
      - checkout

      - setup_remote_docker

      # restores dependencies from cache
      - restore_cache:
          keys:
          - yarn-deps-{{ checksum "yarn.lock" }}

      # restores distribution folder from cache
      - restore_cache:
          keys:
          - packages-dist-{{ .Revision }}-{{ .Branch }}

      # build and push docker prime image
      - run: |
          docker login -u $DOCKER_LOGIN -p $DOCKER_PWD
          docker build . --tag $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:$CIRCLE_SHA1
          if [ "${CIRCLE_BRANCH}" == "master" ]; then
            docker tag $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:$CIRCLE_SHA1 $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:latest
            docker push $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:latest
          else
            docker tag $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:$CIRCLE_SHA1 $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:$CIRCLE_BRANCH
            docker push $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:$CIRCLE_BRANCH
          fi

workflows:
  version: 2
  build-deploy:
    jobs:
    - build
    - docker-build-push:
        context: docker-hub-credentials
        requires:
        - build
        filters:
          branches:
            only:
            - development
            - master
